import React from 'react'
import { Navbar } from './Navbar'

interface PageShellProps {
  children: React.ReactNode
}

export const PageShell: React.FC<PageShellProps> = ({ children }) => {
  return (
    <div className="min-h-screen bg-[#020617] text-slate-200 selection:bg-teal-500/30 selection:text-teal-200 overflow-x-hidden">
      {/* Dynamic Background Elements */}
      <div className="fixed inset-0 pointer-events-none">
        <div className="absolute top-[-10%] left-[-10%] w-[50%] h-[50%] bg-teal-500/10 rounded-full blur-[120px] animate-pulse" />
        <div className="absolute bottom-[-10%] right-[-10%] w-[50%] h-[50%] bg-blue-500/10 rounded-full blur-[120px] animate-pulse" style={{ animationDelay: '1s' }} />
        <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20 mix-blend-overlay" />
      </div>

      <Navbar />
      
      <main className="relative z-10 max-w-7xl mx-auto px-6 py-12 md:py-20">
        {children}
      </main>
      
      <footer className="relative z-10 py-12 border-t border-slate-800/50 text-center">
        <p className="text-slate-500 text-sm font-medium">
          Generated by AStarRoadMaps · Powered by Local AI
        </p>
      </footer>
    </div>
  )
}
