# Use slim base for smaller size
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY docker/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy all source files into the container
COPY . .

# Optional: expose port for web UI like Streamlit
EXPOSE 8501

# Run the app
CMD ["python", "main.py"]
